import React from 'react'
import Layout from "../components/Layout"
import "../styles/global.css"

export const metadata = {
  title: 'Home - RonanDoherty.com',
  description: 'Generated by Next.js',
}

type RootLayoutProps = {
  children: React.ReactNode

}
export default function RootLayout(props: RootLayoutProps) {
  const { children } = props

  return (
    <html lang="en">
      <body className="transition-colors duration-500 bg-white dark:bg-gray-800">
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
